[build]
  publish = "site/public"
  command = "cd site && hugo --minify --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://help.pricewell.com/"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
  from = "https://help.pricewell.io/*"
  to = "https://help.pricewell.com/:splat"
  status = 301
  force = true
