backend:
    name: git-gateway
    branch: master
media_folder: static/img
public_folder: /img
collections:
    - name: 'faq'
      label: 'FAQ'
      folder: 'site/content/faq'
      create: true
      slug: '{{slug}}'
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Keywords', name: 'keywords', widget: 'list' }
    - name: 'features'
      label: 'Features'
      folder: 'site/content/features'
      create: true
      slug: '{{slug}}'
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Keywords', name: 'keywords', widget: 'list' }
    - name: 'features_customer_portal'
      label: 'Features (Customer Portal)'
      folder: 'site/content/features/customer_portal'
      create: true
      slug: '{{slug}}'
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Keywords', name: 'keywords', widget: 'list' }
    - name: 'features_pricing_pages'
      label: 'Features (Pricing Pages)'
      folder: 'site/content/features/pricing_page'
      create: true
      slug: '{{slug}}'
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Keywords', name: 'keywords', widget: 'list' }
    - name: 'features_coupons'
      label: 'Features (Coupons)'
      folder: 'site/content/features/coupons'
      create: true
      slug: '{{slug}}'
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Keywords', name: 'keywords', widget: 'list' }
    - name: 'features_gated_content'
      label: 'Features (Gated Content)'
      folder: 'site/content/features/gated_content'
      create: true
      slug: '{{slug}}'
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Keywords', name: 'keywords', widget: 'list' }
    - name: 'getting-started'
      label: 'Getting Started'
      folder: 'site/content/getting-started'
      create: true
      slug: '{{slug}}'
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Keywords', name: 'keywords', widget: 'list' }
    - name: 'integrations'
      label: 'Integrations'
      folder: 'site/content/integrations'
      create: true
      slug: '{{slug}}'
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Keywords', name: 'keywords', widget: 'list' }
    - name: 'documentation'
      label: 'Documentation'
      folder: 'site/content/documentation'
      create: true
      slug: '{{slug}}'
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Keywords', name: 'keywords', widget: 'list' }
